# Generated by Django 3.2.7 on 2021-09-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('allocation', models.IntegerField(blank=True, null=True)),
                ('equity', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
